from marshmallow import fields, validate
from . import ma

class ProductSchema(ma.Schema):
    id = fields.Integer(required=False) # id is autogenerated
    name = fields.String(required=True, validate=validate.Length(min=1))
    price = fields.Float(required=True, validate=validate.Range(min=0))

# Create an instance of the ProductSchema
product_schema = ProductSchema()
products_schema = ProductSchema(many=True)  # For handling multiple products