swagger: '2.0'
info:
  title: "Ecommerce API"
  description: "API to manage ecommerce interactions"
  version: "1.0.0"
host: "deployment-prep-1.onrender.com" #working on local host
schemes:
  - "https"
consumes:
  - "application/json"
produces:
  - "application/json"
securityDefinitions:
  bearerAuth:
    type: apiKey
    name: Authorization
    in: header
paths: 

  /customers/login:
    post: #Type of request
      tags: 
        - Customers #What catagory this request belongs to
      summary: "Login Endpoint (generates token)"
      description: "Endpoint for user authentication, and token generation"
      parameters:
        - in: "body" #payload comes through the body of the request
          name: "body"
          description: "Credentials for login"
          required: true
          schema:
            $ref: "#/definitions/LoginPayload"
      responses:
        200:
          description: "Login Successful"
          schema:
            $ref: "#/definitions/LoginResponse"
          examples:
            application/json:
              auth_token: "iyhgJHLYFGKHBiYFGgb....."
              message: "Successfully logged in"
              status: "success"
  
  /customers:
    get: 
      tags:
        - Customers
      summary: "Returns all Customers"
      descriptions: "Returns all customers' information (requires token)"
      security:
        - bearerAuth: []
      responses:
        200:
          description: "Retrieved Customers Successfully"
          schema:
            $ref: "#/definitions/AllCustomers"

  /products:
    get: 
      tags:
        - Products
      summary: "Returns all Products"
      descriptions: "Returns all Products' information (requires token)"
      responses:
        200:
          description: "Retrieved Products Successfully"
          schema:
            $ref: "#/definitions/AllProducts"

definitions: 

  LoginPayload:
    type: "object"
    properties:
      username:
        type: "string"
        description: "Customer username"
      password:
        type: "string"
        description: "Customer password"
    required:
      - "username"
      - "password"

  LoginResponse:
    type: "object"
    properties:
      auth_token:
        type: "string"
        description: "Authorization Token"
      message:
        type: "string"
        description: "Successfully Logged In"
      status: 
        type: "string"
        description: "Success"

  AllCustomers:
    type: "object"
    properties:
      name:
        type: "string"
        description: "Customer Name"
      email:
        type: "string"
        description: "Customer Email"
      phone:
        type: "string"
        description: "Customer Phone"
      username:
        type: "string"
        description: "Customer Username"
      role_id:
        type: "integer"
        description: "Customer"

  AllProducts:
    type: "object"
    properties:
      name:
        type: "string"
        description: "Product Name"
      price:
        type: "float"
        desription: "Product Price"
